services:
  postgres:
    container_name: find-friend-pets-DB
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=findfriendpetsDB
    volumes:
      - find_friend_pets_pg_data:/bitnami/postgresql

volumes:
  find_friend_pets_pg_data:
